# Generated by Django 6.0.1 on 2026-02-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_booking_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon_class', models.CharField(help_text="FontAwesome class, e.g., 'fa-shield-alt'", max_length=50)),
                ('tagline', models.CharField(max_length=255)),
                ('offerings', models.TextField(help_text='Enter items separated by newlines')),
                ('why_it_matters', models.TextField()),
                ('target_audience', models.TextField(help_text='Enter items separated by newlines')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
