# Generated by Django 6.0.1 on 2026-02-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='workflow_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in-progress', 'In Progress'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in-progress', 'In Progress'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
