# Generated by Django 6.0.1 on 2026-02-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_booking_workflow_status_contactsubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(max_length=255),
        ),
    ]
